routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/health_check', function() {
    return 'Response From '.env('SERVER_IP', '127.0.0.1');
});

Route::resource('documents', 'DocumentController');

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    protected $fillable=['name', 'desc', 'url', 'uuid'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Session;
use App\Document;
use Webpatser\Uuid\Uuid;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('documents.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $name = $request['name'];
        $desc = $request['desc'];
        
        $document = new Document();
        $document->name = $name;
        $document->desc = $desc;
        $document->uuid = (string) Uuid::generate(4);

        // Replacing whitespace with '-' and taking lowercase
        $file_name = strtolower(str_replace(' ', '-', $name));

        if ($request->hasFile('file')) {
            $file = $request->file('file');
            $file_name_with_extension = time(). $file_name . '.' . $file->getClientOriginalExtension();;
            $filePath = 'files/' . $file_name_with_extension;
            Storage::disk('s3')->put($filePath, file_get_contents($file));
            $fileUrl = Storage::disk('s3')->url($filePath);
            $document->url = $fileUrl;
        }

        $document->save();
        $message = 'Your uploaded file url <a class="alert-link" href="'.route('documents.show', ['uuid' => $document->uuid]).'">'.route('documents.show', ['uuid' => $document->uuid]).'</a>';
        Session::flash('alert-success', $message);
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($uuid)
    {
        $document = Document::where('uuid', $uuid)->first();
        return view('documents.show', compact('document'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/documents/base.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Document Share</title>
  </head>
  <body>

    @yield('content')

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/documents/index.blade.php
@extends('documents.base')

@section('content')
<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <form style="width:350px;" action="{{ route('documents.store') }}" method="POST" enctype="multipart/form-data">
            <img class="mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="100%"
                height="72">
            @csrf

            <div class="form-group">
                <label for="name">Document Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Enter document name"
                    required>
            </div>
            <div class="form-group">
                <label for="desc">Description</label>
                <textarea type="text" class="form-control" name="desc" id="desc" placeholder="Description" required="required"></textarea>
            </div>
            <div class="form-group">
                <label for="file">Select File</label>
                <input type="file" name="file" class="form-control-file" id="file">
            </div>
            <button class="btn btn-lg btn-primary btn-block mt-4" type="submit">Upload Document</button>
            <p class="mt-3 mb-3 text-muted text-center">&copy; 2017-2018</p>
        </form>
    </div>
    <div class="flash-message">
        @foreach (['danger', 'warning', 'success', 'info'] as $msg)
            @if(Session::has('alert-' . $msg))
                <div class="alert alert-{{ $msg }}" role="alert">{!! Session::get('alert-' . $msg) !!}</div>
            @endif
        @endforeach
    </div>
</div>

@endsection

resources/views/documents/show.blade.php
@extends('documents.base')

@section('content')
<div class="container">
    <div class="row">
            <img class="mt-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="100%"
            height="72">
    </div>
    <div class="d-flex justify-content-center mt-2">
        <table style="width:350px;" class="table table-borderless">
            <tbody>
                <tr>
                    <td style="width:150px;">Doucment Name</td>
                    <td>{{ $document->name}}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>{{ $document->desc }}</td>
                </tr>
                <tr>
                    <td>Document URL</td>
                    <td><a href="{{ $document->url }}">File Link</a></td>
                </tr>
                <tr>
                    <td>Uploaded</td>
                    <td>{{ $document->created_at->diffForHumans() }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection